name: akos_app
description: Application AKOS pour trouver des partenaires sportifs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^13.2.5
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env