name: akos_app
description: Application AKOS pour trouver des partenaires sportifs

# Ajoutez cette section
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  go_router: ^13.1.0
  flutter_dotenv: ^5.1.0

  # Ajouter les autres dépendances que vous utiliserez
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env